# Generated by Django 4.0.1 on 2022-04-21 16:11

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('about', tinymce.models.HTMLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Images/')),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'User Accounts', 'verbose_name_plural': 'User Accounts'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us'},
        ),
        migrations.AlterModelOptions(
            name='dmca',
            options={'verbose_name': 'Digital Millennium Copyright Act', 'verbose_name_plural': 'Digital Millennium Copyright Act'},
        ),
        migrations.AlterModelOptions(
            name='privacypolicy',
            options={'verbose_name': 'Our Privacy Policy', 'verbose_name_plural': 'Our Privacy Policy'},
        ),
        migrations.AlterModelOptions(
            name='termsofuse',
            options={'verbose_name': 'Terms Of Use', 'verbose_name_plural': 'Terms Of Use'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profiles', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.RemoveField(
            model_name='account',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='state',
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Images/'),
        ),
        migrations.AddField(
            model_name='termsofuse',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Images/'),
        ),
        migrations.AlterField(
            model_name='dmca',
            name='about',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='about',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='termsofuse',
            name='about',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
